<a href="https://colab.research.google.com/github/pifeldma/MAT-422/blob/main/HW1_2PaigeFeldman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework 1.2 Elements of Linear Algebra


Linear Spaces
Linear Combinations

In [3]:
import numpy as np
vector1 = [ 1, 2, 3, 4]
vector2 = [21, 4, 8, 16]
vector3 = [3, -3, 9, 7]
vector4 = [6, 16, 19, 101]
a = np.array(vector1)
b = np.array(vector2)
c = np.array(vector3)
d = np.array(vector4)
print("Vectors 1, 2, 3, and 4")
print(a,b,c,d)
print(f"Linear Combination: 7*vector1 + 9*vector2 + 2*vector3 + 5*vector4 \n{7*a + 9*b + 2*c + 5*d}")


Vectors 1, 2, 3, and 4
[1 2 3 4] [21  4  8 16] [ 3 -3  9  7] [  6  16  19 101]
Linear Combination: 7*vector1 + 9*vector2 + 2*vector3 + 5*vector4 
[232 124 206 691]


Orthogonality Pythagorean Theorem

In [34]:
import numpy as np
print('Let u,v be orthogonal vectors')
u = [5, 3, 2]
v = [0, 2, -3]
x = np.array(u)
y = np.array(v)
print(x,y)
m1 = np.dot(x, x)
m2 =np.dot(y,y)
print(f'Sum of the norms of the orthogonal vectors: {m1 + m2}')
n = x + y
o = np.dot(n,n)
print(f'the norm of the sum of the orthogonal vectors: {o}')
if o == m1+m2:
  print("So, The Pythagorean Theorem is True")


Let u,v be orthogonal vectors
[5 3 2] [ 0  2 -3]
Sum of the norms of the orthogonal vectors: 51
the norm of the sum of the orthogonal vectors: 51
So, The Pythagorean Theorem is True


Gram-Schmidt Process

In [43]:
import numpy as np
print('Let u,v be linearly independent vectors')
u = [1,1,0]
v = [2,1,1]
x = np.array(u)
y = np.array(v)
print(x,y)
n1 = np.linalg.norm(u)
n2 = np.linalg.norm(v)
new_x = x / n1
innerp = np.dot(x,y) / n1
w = y - innerp*new_x
normw = np.linalg.norm(w)
new_w = w / normw
print(f'Our new vectors e1, e2 are orthonormal and have the same span as u,v')
print(new_x, new_w)

Let u,v be linearly independent vectors
[1 1 0] [2 1 1]
Our new vectors e1, e2 are orthonormal and have the same span as u,v
[0.70710678 0.70710678 0.        ] [ 0.40824829 -0.40824829  0.81649658]


Eigenvalues and Eigenvectors

In [51]:
import numpy as np
a = [[-5,2],[-7,4]]
b = [[1],[1]]
x = np.array(a)
y = np.array(b)
print(f"Vector a: \n{x}")
print(f"Vector b: \n{y}")
dot = np.dot(x,y)
print(f'a*b = \n{dot}')
print(f'Since a*b is a multiple of vector b, b is an eigenvector of a with eigenvalue -3')



Vector a: 
[[-5  2]
 [-7  4]]
Vector b: 
[[1]
 [1]]
a*b = 
[[-3]
 [-3]]
Since a*b is a multiple of vector b, b is an eigenvector of a with eigenvalue -3
