<a href="https://colab.research.google.com/github/pifeldma/MAT-422/blob/main/HW1_3PaigeFeldman.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.3 Linear Regression

QR Decomposition

In [1]:
import numpy as np
print('Let A be a random 3 by 3 matrix')
A = np.random.randint(9, size = (3, 3))
print('When we have two m by n matrices, A and Q, we can find and R such that A = QR.')
Q, R = np.linalg.qr(A)
print('A: \n', A, '\n Q: \n', Q, '\n R: \n', R)

Let A be a random 3 by 3 matrix
When we have two m by n matrices, A and Q, we can find and R such that A = QR.
A: 
 [[5 3 5]
 [7 8 4]
 [6 3 1]] 
 Q: 
 [[-0.47673129  0.33075213 -0.81445092]
 [-0.66742381 -0.73915911  0.09049455]
 [-0.57207755  0.58672552  0.57313213]] 
 R: 
 [[-10.48808848  -8.48581704  -5.62542928]
 [  0.          -3.16083993  -0.71615027]
 [  0.           0.          -3.13714428]]


Least-squares Problems

In [18]:
print('Using our matrices above, we now let b be an m by 1 matrix')
b = np.random.randint(9, size = (3, 1))
print('We want to solve for x in Ax = b by using the least-squares method')
x = np.linalg.lstsq(A, b, rcond = -1)
y = np.matmul(A, x[0])
print('A: \n', A, '\n b: \n', b, '\n x: \n', x[0], '\n Ax \n', y)
print('Our Ax should give us a similar value to b')

Using our matrices above, we now let b be an m by 1 matrix
We want to solve for x in Ax = b by using the least-squares method
A: 
 [[5 3 5]
 [7 8 4]
 [6 3 1]] 
 b: 
 [[0]
 [0]
 [4]] 
 x: 
 [[ 1.07692308]
 [-0.57692308]
 [-0.73076923]] 
 Ax 
 [[ 2.44249065e-15]
 [-1.77635684e-15]
 [ 4.00000000e+00]]
Our Ax should give us a similar value to b
